version: '3'

services:
  weaviate:
    image: docker.io/semitechnologies/weaviate:1.23.1
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    ports:
      - 8080:8080
      - 50051:50051
    volumes:
      - ./data/weaviate:/var/lib/weaviate
    environment:
      GOGC: 800
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: 'weaviate'

  qdrant:
    image: qdrant/qdrant:v1.7.3
    ports:
      - 6333:6333
    volumes:
      - ./data/qdrant:/qdrant/storage
